act: conti
batch_size: 128
conv: GAT
data_dir: 1s_edge_conti128_rain50
edge_fusion: true
epochs: 10000
if_flood: 3
length: 501.0
load_model: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat/10000/retrain
n_sp_layer: 3
n_tp_layer: 3
norm: true
recurrent: Conv1D
resnet: true
roll: 12
save_gap: 1000
seq_in: 5
seq_out: 5
train: true
use_edge: true
