batch_size: 64
conv: 'False'
data_dir: edge
embed_size: 256
env: shunqing
epochs: 20000
if_flood: true
model_dir: 10_30s_20k_res_norm_flood_roll_nn
norm: true
recurrent: Conv1D
resnet: true
roll: true
seq_in: 10
seq_out: 30
train: true
