act: conti
batch_size: 128
conv: GAT
data_dir: 1s_edge_conti128_rain50
edge_fusion: true
epochs: 50000
if_flood: 3
model_dir: 5s_edgef_flood_gat1o
n_sp_layer: 3
n_tp_layer: 3
norm: true
recurrent: Conv1D
resnet: true
save_gap: 5000
seq_in: 5
seq_out: 5
train: true
use_edge: true
