batch_size: 64
conv: GAT
data_dir: edge
epochs: 20000
if_flood: true
model_dir: 15s_20k_10o_edge_res_norm_flood_gat
n_tp_layer: 3
norm: true
order: 10
recurrent: Conv1D
resnet: true
seq_in: 15
seq_out: 15
train: true
use_edge: true
