batch_size: 32
conv: GCN
data_dir: edge
embed_size: 256
env: shunqing
epochs: 20000
model_dir: 10s_20k_edge_res_norm_flood_gcn
norm: true
recurrent: Conv1D
resnet: true
seq_in: 10
seq_out: 10
train: true
use_edge: true
