batch_size: 64
conv: GCN
data_dir: edge
epochs: 20000
if_flood: true
model_dir: 10s_20k_edge_res_norm_flood_gcn
n_tp_layer: 3
norm: true
recurrent: Conv1D
resnet: true
seq_in: 10
seq_out: 10
train: true
use_edge: true
