act: rand3
agent_dir: 5s_20k_rand3_mbrl_observ
batch_size: 64
conv: 'False'
data_dir: ./envs/data/
episodes: 20000
horizon: 60
limit: 19
model_based: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat
norm: true
processes: 4
rain_num: 1
result_dir: ./results/
train: true
use_edge: true
vnet: true
