act: rand
batch_size: 64
conv: GAT
data_dir: act_edge
edge_fusion: true
env: astlingen
epochs: 50000
model_dir: 30s_20k_act_edgef_resn_norm
norm: true
recurrent: Conv1D
resnet: true
seq_in: 30
seq_out: 30
train: true
use_edge: true
