shunqing:
  n_out: 3
  conv: GCNconv
  embed_size: 128
  activation: relu
  n_layer: 3
  recurrent: GRU
  hidden_dim: 64
  seq_len: 6
  resnet: True
  loss_function: MeanSquaredError
  optimizer: Adam
  learning_rate: 0.001
