batch_size: 32
conv: 'False'
data_dir: edge_newset
edge_fusion: true
epochs: 50000
if_flood: 3
model_dir: r1_edgef_flood_nncat_3
n_sp_layer: 3
n_tp_layer: 3
norm: true
recurrent: Conv1D
resnet: true
save_gap: 10000
seq_in: 60
seq_out: 60
train: true
train_event_id: train_id_3.npy
use_edge: true
