act: true
batch_size: 64
conv: GAT
data_dir: act_edge
edge_fusion: true
env: astlingen
epochs: 20000
if_flood: true
model_dir: 10s_20k_act_edge_res_norm_flood
norm: true
recurrent: Conv1D
resnet: true
seq_in: 10
seq_out: 10
train: true
