act: rand
batch_size: 16
conv: GAT
data_dir: edge_rand32_rain50
edge_fusion: true
epochs: 50000
if_flood: 5
length: 1000.0
model_dir: 60s_50k_rand_1000ledgef_res_norm_flood_gat_5lyrs
n_sp_layer: 5
n_tp_layer: 5
norm: true
recurrent: Conv1D
resnet: true
save_gap: 5000
seq_in: 60
seq_out: 60
train: true
use_edge: true
