act: true
batch_size: 32
conv: GAT
data_dir: act
env: RedChicoSur
epochs: 10000
if_flood: true
model_dir: 5s_10k_act_res_norm_flood
norm: true
recurrent: Conv1D
resnet: true
seq_in: 5
seq_out: 5
train: true
