act: conti
batch_size: 128
data_dir: 1s_edge_conti128_rain50
edge_fusion: true
epochs: 50000
if_flood: 5
length: 1000.0
model_dir: 30s_50k_conti_1000ledgef_res_norm_flood_gat_3lyrs2
n_sp_layer: 3
n_tp_layer: 3
norm: true
recurrent: Conv1D
resnet: true
save_gap: 5000
seq_in: 30
seq_out: 30
train: true
use_edge: true
