batch_size: 64
conv: 'False'
data_dir: edge
embed_size: 256
env: shunqing
epochs: 20000
if_flood: true
model_dir: 5s_20k_res_norm_flood_nn
norm: true
recurrent: Conv1D
resnet: true
seq_in: 5
seq_out: 5
train: true
