batch_size: 32
conv: GAT
data_dir: edge_newset
epochs: 20000
if_flood: 3
length: 1200.0
model_dir: r1_flood_gat_5
n_sp_layer: 3
n_tp_layer: 3
norm: true
recurrent: Conv1D
resnet: true
save_gap: 10000
seq_in: 60
seq_out: 60
train: true
train_event_id: train_id_5.npy
use_edge: true
