shunqing:
  # env args
  env: shunqing
  directed: False
  length: 0
  order: 1
  rain_dir: ./envs/config/
  rain_suffix: bpswmm

  # simulate args
  simulate: False
  data_dir: ./envs/data/shunqing/
  act: 'False'
  processes: 5
  repeats: 1
  use_edge: False

  # train args
  train: False
  load_model: False
  edge_fusion: False
  use_adj: False
  model_dir: ./model/shunqing/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  batch_size: 256
  roll: False
  balance: 0
  
  # network args
  norm: False
  n_out: 3
  conv: GCNconv
  embed_size: 128
  n_sp_layer: 2
  dropout: 0.0
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  kernel_size: 3
  n_tp_layer: 2
  seq_in: 6
  seq_out: 1
  resnet: False
  if_flood: False
  epsilon: 0.1

  # test args
  test: False
  result_dir: ./results/shunqing/

RedChicoSur:
  # env args
  env: RedChicoSur
  directed: False
  length: 0
  order: 1
  rain_dir: ./envs/config/
  rain_suffix:

  # simulate args
  simulate: False
  data_dir: ./envs/data/RedChicoSur/
  act: 'False'
  processes: 5
  repeats: 1
  use_edge: False

  # train args
  train: False
  load_model: False
  edge_fusion: False
  use_adj: False
  model_dir: ./model/RedChicoSur/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  batch_size: 256
  roll: False
  balance: 0
  
  # network args
  norm: False
  n_out: 3
  conv: GCNconv
  embed_size: 128
  n_sp_layer: 2
  dropout: 0.0
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  kernel_size: 3
  n_tp_layer: 2
  seq_in: 6
  seq_out: 1
  resnet: False
  if_flood: False
  epsilon: 0.1

  # test args
  test: False
  result_dir: ./results/RedChicoSur/
  rain_dir: ./envs/config/
  rain_suffix:

astlingen:
  # env args
  env: astlingen
  directed: False
  length: 0
  order: 1
  rain_dir: ./envs/config/
  rain_suffix:

  # simulate args
  simulate: False
  data_dir: ./envs/data/astlingen/
  act: 'False'
  processes: 5
  repeats: 1
  use_edge: False

  # train args
  train: False
  load_model: False
  edge_fusion: False
  use_adj: False
  model_dir: ./model/astlingen/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  batch_size: 256
  roll: False
  balance: 0
  
  # network args
  norm: False
  n_out: 3
  conv: GCNconv
  embed_size: 128
  n_sp_layer: 2
  dropout: 0.0
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  kernel_size: 3
  n_tp_layer: 2
  seq_in: 6
  seq_out: 1
  resnet: False
  if_flood: False
  epsilon: 0.1

  # test args
  test: False
  result_dir: ./results/astlingen/

  # MPC args
  control_interval: 5
  setting_duration: 5
  pop_size: 32
  use_current: False
  sampling: 0.4
  crossover:
    - 1.0
    - 3.0
  mutation:
    - 1.0
    - 3.0
  termination:
    - n_eval
    - '256'
  continuous: False
  surrogate: False
  gradient: False

hague:
  # env args
  env: hague
  directed: False
  length: 0
  order: 1
  rain_dir: ./envs/config/
  rain_suffix:

  # simulate args
  simulate: False
  data_dir: ./envs/data/hague/
  act: 'False'
  processes: 5
  repeats: 1
  use_edge: False

  # train args
  train: False
  load_model: False
  # there exists external flow to outfall, so edge_fusion donot work well
  edge_fusion: False
  use_adj: False
  model_dir: ./model/hague/
  ratio: 0.8
  learning_rate: 0.001
  epochs: 500
  batch_size: 256
  roll: False
  balance: 0
  
  # network args
  norm: False
  n_out: 3
  conv: GCNconv
  embed_size: 128
  n_sp_layer: 2
  dropout: 0.0
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  kernel_size: 3
  n_tp_layer: 2
  seq_in: 6
  seq_out: 1
  resnet: False
  if_flood: False
  epsilon: 0.1

  # test args
  test: False
  result_dir: ./results/hague/

  # MPC args
  control_interval: 30
  setting_duration: 15
  pop_size: 32
  use_current: False
  sampling: 0.4
  crossover:
    - 1.0
    - 3.0
  mutation:
    - 1.0
    - 3.0
  termination:
    - n_eval
    - '256'
  continuous: False
  surrogate: False
  gradient: False
