shunqing:
  # simulate args
  simulate: False
  load_data: False
  data_dir: ./envs/data/shunqing/
  act: False
  processes: 5

  # train args
  train: False
  load_model: False
  model_dir: ./model/shunqing/
  ratio: 0.8
  loss_function: MeanSquaredError
  optimizer: Adam
  learning_rate: 0.001
  epochs: 100
  batch_size: 256

  # network args
  norm: False
  n_out: 3
  conv: GCNconv
  embed_size: 128
  n_layer: 3
  activation: relu
  recurrent: GRU
  hidden_dim: 64
  seq_in: 6
  seq_out: 1
  resnet: False
  
  # test args
  test: False
  roll: False
  result_dir: ./results/shunqing/