batch_size: 32
data_dir: ./envs/data/shunqing/60s/
env: shunqing
epochs: 10000
if_flood: true
model_dir: ./model/shunqing/10s_10k_res_norm_roll_flood/
norm: true
recurrent: Conv1D
resnet: true
roll: true
seq_in: 10
seq_out: 10
train: true
