act: rand
batch_size: 16
conv: GAT
data_dir: 1s_edge_rand64_rain50_hp
edge_fusion: true
epochs: 50000
if_flood: 5
length: 200.0
model_dir: 60s_50k_rand_200ledgef_res_norm_flood_gat_pumpweivol_5lyrs
n_sp_layer: 5
n_tp_layer: 5
norm: true
recurrent: Conv1D
resnet: true
save_gap: 5000
seq_in: 60
seq_out: 60
train: true
use_edge: true
