act: rand3
batch_size: 128
data_dir: 1s_edge_rand3128_rain50
edge_fusion: true
epochs: 20000
if_flood: 4
length: 1000.0
model_dir: 30s_20k_3act_1000ledgef_res_norm_flood_gat_3lyrs
n_sp_layer: 3
n_tp_layer: 3
norm: true
recurrent: Conv1D
resnet: true
seq_in: 30
seq_out: 30
train: true
use_edge: true
