act: true
batch_size: 16
conv: GAT
data_dir: act
env: RedChicoSur
epochs: 10000
if_flood: true
model_dir: 5s_act_res_norm_flood_roll
norm: true
recurrent: Conv1D
resnet: true
roll: true
seq_in: 5
seq_out: 5
train: true
