act: true
batch_size: 128
conv: GAT
data_dir: act
env: astlingen
epochs: 5000
if_flood: true
model_dir: 10s_5k_act_res_norm_flood_roll
norm: true
recurrent: Conv1D
resnet: true
roll: true
seq_in: 10
seq_out: 10
train: true
