batch_size: 64
conv: GAT
data_dir: 1min
epochs: 30000
if_flood: true
length: 500.0
load_model: true
model_dir: 10s_20k_res_norm_flood_gat
norm: true
recurrent: Conv1D
resnet: true
seq_in: 10
seq_out: 10
train: true
