act: conti
agent_dir: 5s_10k_conti_mbrl_nosimu
batch_size: 64
conv: GAT
data_dir: ./envs/data/
episodes: 10000
eval_gap: 0
hidden_dim: 128
horizon: 60
length: 501.0
limit: 21
model_based: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat
rain_num: 1
result_dir: ./results/
seq_in: 5
train: true
use_edge: true
