batch_size: 64
conv: GAT
data_dir: edge
edge_fusion: true
env: shunqing
epochs: 20000
model_dir: 5s_20k_edgef_res_norm
norm: true
recurrent: Conv1D
resnet: true
seq_in: 5
seq_out: 5
test: true
train: true
use_edge: true
