act: rand
batch_size: 128
data_dir: 1s_edge_rand128_rain50
edge_fusion: true
epochs: 20000
if_flood: 5
length: 1000.0
model_dir: 60s_20k_7act_1000ledgef_res_norm_flood_gat_5lyrs
n_sp_layer: 5
n_tp_layer: 5
norm: true
recurrent: Conv1D
resnet: true
seq_in: 60
seq_out: 60
train: true
use_edge: true
