act: rand3
agent_dir: 5s_20k_rand3_mbrl_observ_tune_cri
batch_size: 64
conv: 'False'
cri_lr: 0.0001
data_dir: ./envs/data/
episodes: 20000
horizon: 60
limit: 19
model_based: true
model_dir: 5s_20k_conti_500ledgef_res_norm_flood_gat
n_layer: 5
norm: true
processes: 2
rain_num: 1
result_dir: ./results/
train: true
update_interval: 0.001
use_edge: true
vnet: true
