batch_size: 64
conv: GAT
data_dir: edge
embed_size: 256
env: shunqing
epochs: 20000
if_flood: true
model_dir: 5s_20k_res_norm_flood_GAT
norm: true
recurrent: Conv1D
repeats: 1
resnet: true
seq_in: 5
seq_out: 5
train: true
