act: rand3
agent_dir: ./agent/astlingen/5s_10k_rand3_mbrl
batch_size: 64
conv: GAT
data_dir: ./envs/data/
env: astlingen
episodes: 10000
eval_gap: 0
hidden_dim: 128
horizon: 60
length: 501
limit: 23
load_agent: false
model_based: true
model_dir: ./model/astlingen/5s_20k_conti_500ledgef_res_norm_flood_gat/
processes: 2
rain_num: 1
recurrent: Conv1D
result_dir: ./results/
seq_in: 5
setting_duration: 5
start_gap: 0
train: true
use_edge: true
vnet: true
