act: rand3
agent_dir: 5s_20k_rand3_mfrl_observ
batch_size: 64
conv: 'False'
data_dir: 1s_edge_conti128_rain50
episodes: 20000
horizon: 60
limit: 19
model_dir: ./model/
norm: true
processes: 4
rain_num: 1
result_dir: ./results/
sample_gap: 5
train: true
use_edge: true
vnet: true
