batch_size: 32
conv: 'False'
data_dir: edge
edge_fusion: true
epochs: 50000
if_flood: 3
length: 1000.0
model_dir: 60s_50k_1000l_edgef_res_norm_flood_nn_cat_6ly
n_sp_layer: 6
n_tp_layer: 3
norm: true
recurrent: Conv1D
resnet: true
save_gap: 10000
seq_in: 60
seq_out: 60
train: true
use_edge: true
