act: rand
batch_size: 128
conv: 'False'
data_dir: act10_edge_rain50
edge_fusion: true
epochs: 20000
if_flood: true
length: 1000.0
model_dir: 30s_20k_1000l_edgef_res_norm_flood_nn
n_tp_layer: 4
norm: true
recurrent: Conv1D
resnet: true
seq_in: 30
seq_out: 30
train: true
use_edge: true
