# Configuration file for scenario astlingen
# name of scearnio
env_name: astlingen
# if env contains actions
act: True
# time step (min)
control_interval: 1
# state definitions
# global state definitions
global_state:
  - !!python/tuple
    - nodes
    - depthN
  - !!python/tuple
    - nodes
    - cuminflow
  - !!python/tuple
    - nodes
    - totaloutflow
  - !!python/tuple
    - nodes
    - cum_lateral_inflow

# Action space
action_space:
  V2:
    !!python/tuple
    # - 0.1075
    # - 0.2366
    # - 0.3657
    # - 0.4948
    # - 0.6239
    # - 0.7530
    # - 0.8821
    # - 1.0
    - 0.1075
    - 0.2366
    - 1.0
  V3:
    !!python/tuple
    - 0.3159
    - 0.6508
    - 1.0
    # - 0.3159
    # - 0.4275
    # - 0.5392
    # - 0.6508
    # - 0.7624
    # - 0.8741
    # - 1.0
  V4:
    !!python/tuple
    - 0.1894
    - 0.3523
    - 1.0
    # - 0.1894
    # - 0.3523
    # - 0.5152
    # - 0.6781
    # - 0.8410
    # - 1.0
  V6:
    !!python/tuple
    - 0.1687
    - 0.4303
    - 1.0
    # - 0.1687
    # - 0.2995
    # - 0.4303
    # - 0.5611
    # - 0.6919
    # - 0.8227
    # - 1.0

# Performance Targets
performance_targets:
  - !!python/tuple
    - nodes
    - cumflooding
    - 1

# Rainfall scenario parameters
rainfall:
  func: generate_split_file
  filedir: ./envs/network/astlingen/astlingen
  rainfall_timeseries: ./envs/config/ast_rain.csv # rainfall timeseries data
  rainfall_events: ./envs/config/ast_train_events.csv # rainfall timeseries data
  MIET: 120 # minimum interevent time (min)
  duration_range:  # rainfall duration sampling range (min)
    - 60
    - 100000
  precipitation_range: # rainfall precipitation sampling range (mm)
    - 5
    - 15
  date_range: # rainfall precipitation sampling range (mm)
    - 01/01/2000
    - 12/31/2009
  replace_rain: False
  
