# Configuration file for scenario shunqing
# name of scearnio
env_name: shunqing
# if env contains actions
act: False
# time step (min)
interval: 1
# state definitions
# global state definitions
global_state:
  - !!python/tuple
    - nodes
    - depthN
  - !!python/tuple
    - nodes
    - totalinflow
  - !!python/tuple
    - nodes
    - totaloutflow
  - !!python/tuple
    - nodes
    - lateralinflow
  - !!python/tuple
    - links
    - depthL
  - !!python/tuple
    - links
    - volumeL
  - !!python/tuple
    - links
    - flow
  - !!python/tuple
    - links
    - setting

    
states:
  - !!python/tuple
    - jd1
    - depthN
  - !!python/tuple
    - jd2
    - depthN
  - !!python/tuple
    - jd3
    - depthN

# Performance Targets
performance_targets:
  - !!python/tuple
    - nodes
    - cumflooding
    - 1

flood:
  - !!python/tuple
    - nodes
    - cumflooding
    
# Rainfall scenario parameters
rainfall:
  func: generate_file
  suffix: bpswmm
  filedir: ./envs/network/shunqing/
  MIET: 1
  gage: RainGage

# if time-variant outlet boundary
tide: False

# Model predictive parameters
prediction:
  control_horizon: 5  # Control horizon (min)
  eval_horizon: 5 # Evaluation horizon (min)
  hsf_dir: hsf # file path to save the hotstart file
  eval_dir: eval # file path to save the evaluation file
  suffix: mpc_eval_ # suffix of the evaluation file

