act: conti
agent_dir: ./agent/astlingen/5s_10k_conti_mbrl
batch_size: 2
conv: GAT
cri_lr: 0.001
env: astlingen
episodes: 1000
eval_gap: 10
horizon: 60
length: 501
max_capacity: 524288
model_dir: ./model/astlingen/5s_20k_conti_500ledgef_res_norm_flood_gat/
processes: 2
rain_dir: ./envs/config/ast_test1_events.csv
rain_num: 1
recurrent: Conv1D
result_dir: ./results/astlingen/60s_10k_conti_policy2007
seq_in: 5
setting_duration: 5
test: false
train: true
use_edge: true
