batch_size: 64
conv: GAT
data_dir: edge
edge_fusion: true
env: shunqing
epochs: 10000
if_flood: true
model_dir: 5s_edge_res_norm_flood
norm: true
recurrent: Conv1D
resnet: true
seq_in: 5
seq_out: 5
train: true
use_adj: false
