batch_size: 64
conv: GAT
data_dir: edge
env: shunqing
epochs: 20000
if_flood: true
model_dir: 5s_20k_edge_res_norm_flood
norm: true
recurrent: Conv1D
resnet: true
result_dir: 5s_edge_res_norm_flood
seq_in: 5
seq_out: 5
test: true
train: true
use_edge: true
