balance: 0.3
batch_size: 128
data_dir: ./envs/data/shunqing/60s/
env: shunqing
epochs: 5000
if_flood: true
model_dir: ./model/shunqing/10s_5k_res_norm_bal_flood/
norm: true
resnet: true
seq_in: 10
seq_out: 10
train: true
